version: "3.8"
services:
  dev-data:
    image: postgres:15.0
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgadmin
      - POSTGRES_DB=geo_pro
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  dev-adminer:
    image: adminer
    ports:
      - 8088:8080
