version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: nestjs.dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./dist:/app/dist
      - ./images:/app/images
